version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    ports:
    - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:4.1.0
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
    - 9092:9092
    depends_on:
    - zookeeper
  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.1.0
    environment:
    - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
    - KAFKA_REST_SCHEMA_REGISTRY_URL=http://kafka:8081
    - KAFKA_REST_HOST_NAME=kafka
    ports:
    - 8082:8082
    depends_on:
    - kafka
  kafka-ui:
    image: landoop/kafka-topics-ui
    environment:
    - KAFKA_REST_PROXY_URL=http://kafka:8082
    - PROXY=true
    ports:
    - 8000:8000
    depends_on:
    - kafka-rest
